global_costmap:
    global_frame: odom
    robot_base_frame: base_link
    plugins:
        - {name: unrolling_layer,       type: "unrolling_layer::UnrollingLayer"}
#        - {name: static_layer,       type: "costmap_2d::StaticLayer"}
        - {name: inflation_layer,       type: "costmap_2d::InflationLayer"}
        - {name: fakecone_layer,        type: "fakecone_layer::FakeconeLayer"}
    publish_frequency: 5.0
    footprint: [[-0.24,0.32],[0.72,0.32],[0.72,-0.32],[-0.24,-0.32]]
    width: 200
    height: 200
    origin_x: -100
    origin_y: -100
    update_frequency: 10
    track_unknown_space: false
    unknown_cost_value: 30
    rolling_window: false
    resolution: 0.1
    static_layer:
        map_topic: "/move_base_flex/local_costmap/costmap"
        subscribe_to_updates: true
    inflation_layer:
        inflation_radius: 5.0
unrolling_layer:
    topic: "/move_base_flex/local_costmap/costmap"
